# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window_split.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QSpacerItem, QSplitter,
    QStatusBar, QTabWidget, QToolButton, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        self.actionOpenImage = QAction(MainWindow)
        self.actionOpenImage.setObjectName(u"actionOpenImage")
        self.actionPreview = QAction(MainWindow)
        self.actionPreview.setObjectName(u"actionPreview")
        self.actionExportCsv = QAction(MainWindow)
        self.actionExportCsv.setObjectName(u"actionExportCsv")
        self.actionOpenCamera = QAction(MainWindow)
        self.actionOpenCamera.setObjectName(u"actionOpenCamera")
        self.actionRunFull = QAction(MainWindow)
        self.actionRunFull.setObjectName(u"actionRunFull")
        self.actionRunSelected = QAction(MainWindow)
        self.actionRunSelected.setObjectName(u"actionRunSelected")
        self.actionStop = QAction(MainWindow)
        self.actionStop.setObjectName(u"actionStop")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionOverlay = QAction(MainWindow)
        self.actionOverlay.setObjectName(u"actionOverlay")
        icon = QIcon()
        icon.addFile(u":/icons/overlay.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOverlay.setIcon(icon)
        self.actionConfigOverlay = QAction(MainWindow)
        self.actionConfigOverlay.setObjectName(u"actionConfigOverlay")
        self.actionConfigMarkers = QAction(MainWindow)
        self.actionConfigMarkers.setObjectName(u"actionConfigMarkers")
        self.actionConfigPipeline = QAction(MainWindow)
        self.actionConfigPipeline.setObjectName(u"actionConfigPipeline")
        self.actionConfigPreprocessing = QAction(MainWindow)
        self.actionConfigPreprocessing.setObjectName(u"actionConfigPreprocessing")
        self.actionConfigEdgeDetection = QAction(MainWindow)
        self.actionConfigEdgeDetection.setObjectName(u"actionConfigEdgeDetection")
        self.actionConfigGeometry = QAction(MainWindow)
        self.actionConfigGeometry.setObjectName(u"actionConfigGeometry")
        self.actionConfigPhysics = QAction(MainWindow)
        self.actionConfigPhysics.setObjectName(u"actionConfigPhysics")
        self.actionConfigAcquisition = QAction(MainWindow)
        self.actionConfigAcquisition.setObjectName(u"actionConfigAcquisition")
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setNativeMenuBar(False)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuConfig = QMenu(self.menubar)
        self.menuConfig.setObjectName(u"menuConfig")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuRun = QMenu(self.menubar)
        self.menuRun.setObjectName(u"menuRun")
        self.menuPlugins = QMenu(self.menubar)
        self.menuPlugins.setObjectName(u"menuPlugins")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralLayout = QVBoxLayout(self.centralwidget)
        self.centralLayout.setObjectName(u"centralLayout")
        self.workflowBar = QWidget(self.centralwidget)
        self.workflowBar.setObjectName(u"workflowBar")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workflowBar.sizePolicy().hasHeightForWidth())
        self.workflowBar.setSizePolicy(sizePolicy)
        self.workflowBar.setMaximumSize(QSize(16777215, 48))
        self.workflowBarLayout = QHBoxLayout(self.workflowBar)
        self.workflowBarLayout.setSpacing(8)
        self.workflowBarLayout.setObjectName(u"workflowBarLayout")
        self.workflowBarLayout.setContentsMargins(12, 8, 12, 8)
        self.actionOpenImageBtn = QToolButton(self.workflowBar)
        self.actionOpenImageBtn.setObjectName(u"actionOpenImageBtn")
        self.actionOpenImageBtn.setAutoRaise(True)

        self.workflowBarLayout.addWidget(self.actionOpenImageBtn)

        self.workflowAutoCalibrateBtn = QToolButton(self.workflowBar)
        self.workflowAutoCalibrateBtn.setObjectName(u"workflowAutoCalibrateBtn")
        self.workflowAutoCalibrateBtn.setAutoRaise(True)

        self.workflowBarLayout.addWidget(self.workflowAutoCalibrateBtn)

        self.actionRunBtn = QToolButton(self.workflowBar)
        self.actionRunBtn.setObjectName(u"actionRunBtn")
        self.actionRunBtn.setAutoRaise(True)

        self.workflowBarLayout.addWidget(self.actionRunBtn)

        self.actionExportCsvBtn = QToolButton(self.workflowBar)
        self.actionExportCsvBtn.setObjectName(u"actionExportCsvBtn")
        self.actionExportCsvBtn.setAutoRaise(True)

        self.workflowBarLayout.addWidget(self.actionExportCsvBtn)

        self.workflowAdvancedBtn = QToolButton(self.workflowBar)
        self.workflowAdvancedBtn.setObjectName(u"workflowAdvancedBtn")
        self.workflowAdvancedBtn.setCheckable(True)
        self.workflowAdvancedBtn.setAutoRaise(True)

        self.workflowBarLayout.addWidget(self.workflowAdvancedBtn)

        self.workflowSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.workflowBarLayout.addItem(self.workflowSpacer)


        self.centralLayout.addWidget(self.workflowBar)

        self.rootSplitter = QSplitter(self.centralwidget)
        self.rootSplitter.setObjectName(u"rootSplitter")
        self.rootSplitter.setOrientation(Qt.Horizontal)
        self.setupHost = QWidget(self.rootSplitter)
        self.setupHost.setObjectName(u"setupHost")
        self.setupHostLayout = QVBoxLayout(self.setupHost)
        self.setupHostLayout.setObjectName(u"setupHostLayout")
        self.setupHostLayout.setContentsMargins(0, 0, 0, 0)
        self.rootSplitter.addWidget(self.setupHost)
        self.workbenchHost = QWidget(self.rootSplitter)
        self.workbenchHost.setObjectName(u"workbenchHost")
        self.workbenchHostLayout = QVBoxLayout(self.workbenchHost)
        self.workbenchHostLayout.setObjectName(u"workbenchHostLayout")
        self.workbenchHostLayout.setContentsMargins(0, 0, 0, 0)
        self.workbenchSplitter = QSplitter(self.workbenchHost)
        self.workbenchSplitter.setObjectName(u"workbenchSplitter")
        self.workbenchSplitter.setOrientation(Qt.Vertical)
        self.previewResultsSplitter = QSplitter(self.workbenchSplitter)
        self.previewResultsSplitter.setObjectName(u"previewResultsSplitter")
        self.previewResultsSplitter.setOrientation(Qt.Horizontal)
        self.previewHost = QWidget(self.previewResultsSplitter)
        self.previewHost.setObjectName(u"previewHost")
        self.previewHostLayout = QVBoxLayout(self.previewHost)
        self.previewHostLayout.setObjectName(u"previewHostLayout")
        self.previewHostLayout.setContentsMargins(0, 0, 0, 0)
        self.previewResultsSplitter.addWidget(self.previewHost)
        self.keyResultsHost = QWidget(self.previewResultsSplitter)
        self.keyResultsHost.setObjectName(u"keyResultsHost")
        self.keyResultsHost.setMinimumSize(QSize(260, 0))
        self.keyResultsHost.setMaximumSize(QSize(340, 16777215))
        self.keyResultsHostLayout = QVBoxLayout(self.keyResultsHost)
        self.keyResultsHostLayout.setObjectName(u"keyResultsHostLayout")
        self.keyResultsHostLayout.setContentsMargins(8, 8, 8, 8)
        self.previewResultsSplitter.addWidget(self.keyResultsHost)
        self.workbenchSplitter.addWidget(self.previewResultsSplitter)
        self.inspectTabs = QTabWidget(self.workbenchSplitter)
        self.inspectTabs.setObjectName(u"inspectTabs")
        self.inspectTabs.setTabPosition(QTabWidget.North)
        self.resultsTab = QWidget()
        self.resultsTab.setObjectName(u"resultsTab")
        self.resultsHostLayout = QVBoxLayout(self.resultsTab)
        self.resultsHostLayout.setObjectName(u"resultsHostLayout")
        self.inspectTabs.addTab(self.resultsTab, "")
        self.residualsTab = QWidget()
        self.residualsTab.setObjectName(u"residualsTab")
        self.residualsHostLayout = QVBoxLayout(self.residualsTab)
        self.residualsHostLayout.setObjectName(u"residualsHostLayout")
        self.inspectTabs.addTab(self.residualsTab, "")
        self.timingsTab = QWidget()
        self.timingsTab.setObjectName(u"timingsTab")
        self.timingsHostLayout = QVBoxLayout(self.timingsTab)
        self.timingsHostLayout.setObjectName(u"timingsHostLayout")
        self.inspectTabs.addTab(self.timingsTab, "")
        self.logTab = QWidget()
        self.logTab.setObjectName(u"logTab")
        self.logHostLayout = QVBoxLayout(self.logTab)
        self.logHostLayout.setObjectName(u"logHostLayout")
        self.inspectTabs.addTab(self.logTab, "")
        self.workbenchSplitter.addWidget(self.inspectTabs)

        self.workbenchHostLayout.addWidget(self.workbenchSplitter)

        self.rootSplitter.addWidget(self.workbenchHost)

        self.centralLayout.addWidget(self.rootSplitter)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConfig.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuPlugins.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpenImage)
        self.menuFile.addAction(self.actionOpenCamera)
        self.menuFile.addAction(self.actionExportCsv)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuConfig.addAction(self.actionConfigOverlay)
        self.menuConfig.addAction(self.actionConfigMarkers)
        self.menuConfig.addSeparator()
        self.menuConfig.addAction(self.actionConfigPipeline)
        self.menuConfig.addSeparator()
        self.menuConfig.addAction(self.actionConfigPreprocessing)
        self.menuConfig.addAction(self.actionConfigEdgeDetection)
        self.menuConfig.addAction(self.actionConfigGeometry)
        self.menuConfig.addAction(self.actionConfigPhysics)
        self.menuConfig.addAction(self.actionConfigAcquisition)
        self.menuView.addAction(self.actionOverlay)
        self.menuRun.addAction(self.actionPreview)
        self.menuRun.addAction(self.actionRunFull)
        self.menuRun.addAction(self.actionRunSelected)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionStop)
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Menipy ADSA", None))
        self.actionOpenImage.setText(QCoreApplication.translate("MainWindow", u"Open &Image\u2026", None))
#if QT_CONFIG(shortcut)
        self.actionOpenImage.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionPreview.setText(QCoreApplication.translate("MainWindow", u"&Preview", None))
#if QT_CONFIG(shortcut)
        self.actionPreview.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionExportCsv.setText(QCoreApplication.translate("MainWindow", u"Export &CSV\u2026", None))
        self.actionOpenCamera.setText(QCoreApplication.translate("MainWindow", u"Open &Camera", None))
        self.actionRunFull.setText(QCoreApplication.translate("MainWindow", u"Run &Full", None))
#if QT_CONFIG(shortcut)
        self.actionRunFull.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionRunSelected.setText(QCoreApplication.translate("MainWindow", u"Run &Selected", None))
#if QT_CONFIG(shortcut)
        self.actionRunSelected.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionStop.setText(QCoreApplication.translate("MainWindow", u"&Stop", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"&Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"&About", None))
        self.actionOverlay.setText(QCoreApplication.translate("MainWindow", u"&Overlay\u2026", None))
#if QT_CONFIG(shortcut)
        self.actionOverlay.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+O", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.actionOverlay.setToolTip(QCoreApplication.translate("MainWindow", u"Open overlay configuration and preview overlay styling", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionOverlay.setStatusTip(QCoreApplication.translate("MainWindow", u"Configure overlay appearance", None))
#endif // QT_CONFIG(statustip)
        self.actionConfigOverlay.setText(QCoreApplication.translate("MainWindow", u"Overlay Appearance\u2026", None))
#if QT_CONFIG(shortcut)
        self.actionConfigOverlay.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionConfigMarkers.setText(QCoreApplication.translate("MainWindow", u"Marker Display\u2026", None))
        self.actionConfigPipeline.setText(QCoreApplication.translate("MainWindow", u"Pipeline Settings\u2026", None))
        self.actionConfigPreprocessing.setText(QCoreApplication.translate("MainWindow", u"Preprocessing\u2026", None))
        self.actionConfigEdgeDetection.setText(QCoreApplication.translate("MainWindow", u"Edge Detection\u2026", None))
        self.actionConfigGeometry.setText(QCoreApplication.translate("MainWindow", u"Geometry\u2026", None))
        self.actionConfigPhysics.setText(QCoreApplication.translate("MainWindow", u"Physics\u2026", None))
        self.actionConfigAcquisition.setText(QCoreApplication.translate("MainWindow", u"Acquisition\u2026", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menuConfig.setTitle(QCoreApplication.translate("MainWindow", u"&Config", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"&View", None))
        self.menuRun.setTitle(QCoreApplication.translate("MainWindow", u"&Run", None))
        self.menuPlugins.setTitle(QCoreApplication.translate("MainWindow", u"&Plugins", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.actionOpenImageBtn.setText(QCoreApplication.translate("MainWindow", u"Open Image", None))
#if QT_CONFIG(tooltip)
        self.actionOpenImageBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Load a single image into the active analysis", None))
#endif // QT_CONFIG(tooltip)
        self.workflowAutoCalibrateBtn.setText(QCoreApplication.translate("MainWindow", u"Auto-Calibrate", None))
#if QT_CONFIG(tooltip)
        self.workflowAutoCalibrateBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Detect calibration regions from the current image", None))
#endif // QT_CONFIG(tooltip)
        self.actionRunBtn.setText(QCoreApplication.translate("MainWindow", u"Run Analysis", None))
#if QT_CONFIG(tooltip)
        self.actionRunBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Run the configured analysis pipeline", None))
#endif // QT_CONFIG(tooltip)
        self.actionExportCsvBtn.setText(QCoreApplication.translate("MainWindow", u"Export CSV", None))
#if QT_CONFIG(tooltip)
        self.actionExportCsvBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Export the visible results table to CSV", None))
#endif // QT_CONFIG(tooltip)
        self.workflowAdvancedBtn.setText(QCoreApplication.translate("MainWindow", u"Advanced +", None))
#if QT_CONFIG(tooltip)
        self.workflowAdvancedBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Show SOP, stages, diagnostics, and logs", None))
#endif // QT_CONFIG(tooltip)
        self.inspectTabs.setTabText(self.inspectTabs.indexOf(self.resultsTab), QCoreApplication.translate("MainWindow", u"Results", None))
        self.inspectTabs.setTabText(self.inspectTabs.indexOf(self.residualsTab), QCoreApplication.translate("MainWindow", u"Residuals", None))
        self.inspectTabs.setTabText(self.inspectTabs.indexOf(self.timingsTab), QCoreApplication.translate("MainWindow", u"Timings", None))
        self.inspectTabs.setTabText(self.inspectTabs.indexOf(self.logTab), QCoreApplication.translate("MainWindow", u"Log", None))
    # retranslateUi

